### ISSUE TITLE
Minor Text cleanups

### ISSUE THREAD

**Issue by Orv** [smsearcy/mesh-info#46]
Under Bands -

5GHz:  --->  5 GHz:
2GHz:  --->  2 GHz:
3GHZ:  --->  3 2GHz:
:  ---> No RF   (if that's what it actually means)

**Comment by smsearcy** [comment]
I was making a change this afternoon to have blank be "N/A", but I prefer your wording of "No RF".  I'm glad I didn't merge that one too fast.

**Comment by smsearcy** [comment]
@Orv is there supposed to be a "2" in the description for 3 GHz?

**Comment by Orv** [comment]
Nah - that's just a typo - sometimes I kant tipe...  Sorry!

**Comment by smsearcy** [comment]
Completely understand!  At first I wasn't sure if it was supposed to be 3.2 GHz, but looking at MeshMap, I think its 3.4 GHz. 

I had left a TODO in the code to use an enumeration for the bands, rather than string values. I think I'm going to take this opportunity to do that so I can separate the values in the DB from what is presented in the UI (that should make any future changes to the labels in the UI easier, and prevent issues like the wrong node color).  

This would have been easier if I always calculated the band from the other node information, but it seemed useful to have it in the DB table for querying.  But it's there so I'll leave it.
